# PoC for using https://github.com/cdr/code-server with formuladb dev environment
FROM codercom/code-server

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
    && chmod +x ./kubectl \
    && sudo mv ./kubectl /usr/local/bin/kubectl

RUN curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 \
    && chmod +x skaffold \
    && sudo mv skaffold /usr/local/bin/skaffold

RUN sudo apt-get update && sudo apt-get install -y tmux socat

#Stuff to make it work in WSL+k3d
#copy kubeconfig.yml
#export KUBECONFIG
#we need to connect to the k8s cluster running in k3d in docker for windows
#the certificate is on localhost:6443 so we need socat to forward the connection to the host IP:6443
#socat TCP-LISTEN:6443,fork TCP:192.168.1.3:6443
#kubectl get pods
#copy $HOME/.docker/config.json to .docker-config.json
#kubectl create secret generic regcred --from-file=.dockerconfigjson=.docker-config.json --type=kubernetes.io/dockerconfigjson
#sudo apt-get install -y docker.io
#
# we need to connect docker to the docker daemon running in Hyper V
# the docker daemon listens on 127.0.0.1 so we need to run this in WSL on windows:
# socat TCP-LISTEN:2376,fork TCP:127.0.0.1:2375
# then:
#export DOCKER_HOST=tcp://192.168.1.3:2375
#docker ps
#skaffold dev -p dev --port-forward=true
#sudo apt-get install -y nodejs npm
#remove deploy-k3s.sh from serve.sh
#remove `while ! k3d get-kubeconfig...` from package.json for dev:watch script
#npm run serve

#rm .dockerignore because we want to copy everything inside the container
ADD . /home/coder/project
