import { BaseObj } from "./base_obj";

export class BaseObjHistory extends BaseObj {
    //last transaction $id applied to main object
    rev$?: string;

    //list of transactions for this object
    trs$?: [{
        //id$ is a TimeUUID generated by the FormulaDB Engine
        [id$: string]: {
            diff: any,
            state: 'BEGIN' | 'PRE_COMMIT' | 'COMMIT'
        };
    }]
}
