apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: be
  name: be
spec:
  ports:
  - name: "9229"
    port: 9229
    targetPort: 9229
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: be
status:
  loadBalancer: {}
