export const DefaultDictionary = [
    { _id: '$I18n~~Enable-Developer-Mode', en: 'Enable Developer Mode' , },
    { _id: '$I18n~~Disable-Developer-Mode', en: 'Disable Developer Mode' , },

    { _id: '$I18n~~hd_cover', en: "Cover" , },
    { _id: '$I18n~~hd_carousel', en: "Carousel" , },
    { _id: '$I18n~~hd_split' , en: "Split" , },

    { _id: '$I18n~~ly_spreadsheet', en: "Spreadsheet" , },
    { _id: '$I18n~~ly_admin', en: "Admin" , },
    { _id: '$I18n~~ly_form', en: "Form" , },
    { _id: '$I18n~~ly_landing' , en: "Landing" , },
    { _id: '$I18n~~ly_fpattern', en: "F-Pattern" , },
    { _id: '$I18n~~ly_zpattern', en: "Z-Pattern" , },
    { _id: '$I18n~~ly_zigzag', en: "Zig Zag Pattern" , },
    { _id: '$I18n~~ly_cards', en: "Cards" , },
    { _id: '$I18n~~ly_grid', en: "Grid" , },
    { _id: '$I18n~~ly_mosaic' , en: "Mosaic" , },
    { _id: '$I18n~~ly_magazine', en: "Magazine" , },
    { _id: '$I18n~~ly_container_free' , en: "Container Free" , },
    { _id: '$I18n~~ly_horizontal_symetry', en: "Horizontal Symetry" , },
    { _id: '$I18n~~ly_radial_symetry', en: "Radial symetry" , },

    { _id: '$I18n~~ly_asymetry', en: "Asymetry" , },
    { _id: '$I18n~~lk_Friendly', en: "Friendly" , },
    { _id: '$I18n~~lk_Approachable', en: "Approachable" , },
    { _id: '$I18n~~lk_Professional', en: "Professional" , },
    { _id: '$I18n~~lk_Experienced', en: "Experienced" , },
    { _id: '$I18n~~lk_Upscale', en: "Upscale" , },
    { _id: '$I18n~~lk_Exclusive', en: "Exclusive" , },
    { _id: '$I18n~~lk_CuttingEdge', en: "Cutting Edge" , },
    { _id: '$I18n~~lk_Stylish', en: "Stylish" , },
    { _id: '$I18n~~lk_HighTech', en: "High Tech" , },
    { _id: '$I18n~~lk_Powerful', en: "Powerful" , },

    { _id: '$I18n~~add-table', en: "Add table" , },
    { _id: '$I18n~~add-child-table-to', en: "Add child table to $PARAM$" , },
    { _id: '$I18n~~add-column-to', en: "Add column to $PARAM$" , },
    { _id: '$I18n~~add-column', en: "Add column" , },
    { _id: '$I18n~~del-table', en: "Delete table" , },
    { _id: '$I18n~~del-column', en: "Delete column" , },
];
