FROM google/cloud-sdk

# Skaffold needs local registry config
# https://github.com/GoogleContainerTools/skaffold/issues/2840#issuecomment-543175867
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && \
    mv kustomize /usr/local/bin/kustomize && \
    curl -o /usr/local/bin/skaffold https://storage.googleapis.com/skaffold/releases/v1.5.0/skaffold-linux-amd64 && \
    chmod +x /usr/local/bin/skaffold && mkdir ~/.docker && \
    curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get update && apt-get install -y ./google-chrome-stable_current_amd64.deb && \
    curl -sL https://deb.nodesource.com/setup_10.x |  bash - && \
    apt-get install -y nodejs && \
    apt-get install -y build-essential jq

COPY docker-config.json /root/.docker/config.json:
