@startuml formula_engine_architecture

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v1.0.0
!includeurl ICONURL/font-awesome/database.puml
!includeurl ICONURL/font-awesome/long_arrow_right.puml

title __Formula Engine Architecture__\n\
A Transactional Stream Processing Engine

actor User

box "Formula DB Engine"
    participant "Actions\n<$database{scale=0.5}>db\n<$long_arrow_right{scale=0.5}>stream" as Actions
    participant "ExecutionEngine" as ExecutionEngine

    participant "Data\n<$database{scale=0.5}>db\n<$long_arrow_right{scale=0.5}>stream" as Data
end box

note right User: synchronous REST communication \n\
  even if FormulaDB works in an asynchronous manner internally

User --> Actions: MwzEvents{BaseObj}

note over Actions: partition by Action _id
note over Data: partition by BaseObj _id
Actions --> ExecutionEngine: changelog stream

note over ExecutionEngine: break down Action into Transactions\n\
and break down each Transaction into Operations
ExecutionEngine --> Data: Operation{BaseObj}

@enduml
