@startuml

actor User
box "Client UI"
    participant AppCmp
    participant NavCmp
    participant TableCmp
    participant FormCmp
end box
box "Client Logic"
    participant AppEffects
    participant Store
end box
box "Server"
    participant MwzEngine
    participant EventDB
    participant DataDB
end box

note right of User: When_user_first_accesses_the_app
User -> AppCmp: navigate /

note right of User: Then_navigation_should_show_all_current_tables
AppCmp -> AppCmp: 
NavCmp -> NavCmp: display sidebar

note right of User: When_user_navigates_to_a_service_form
User -> NavCmp: select ServiceForm
'if this sets up replication from the server, then perhaps it is better to be a POST becase it will allocate resources on the server
User <- TableCmp: table of ServiceForms
User -> TableCmp: select ServiceForm

note right of User: Then_the_form_page_should_be_displayed
User <- FormCmp: edit ServiceForm

note right of User: When_user_updates_the_requested_quantity_of_a_product_list_item
note right of User: When_user_updates_the_requested_quantity_of_a_product_list_item
note right of User: Then_user_will_see_the_reserved_quantity_and_stock_computed_by_the_engine
note right of User: TODO_user_creates_new_service_form

@enduml
