@startuml uimetadata_flow

title
What is special about Couldev: this standard looking ERP software is implemented using a simple language 
  accessible to business people
end title

actor User
box "Client UI"
    participant FormCmp
    participant TableCmp
    participant AppEffects
    participant PouchDB
    participant Store
end box
box "Server"
    participant MwzEngine
    participant EventDB
    participant DataDB
end box

note right of User: TODO_use_editor_to_change_order_of_columns_in_table
note right of User: TOOD_use_editor_to_change_form_layout\n\
    data binding rules with the entity must be obeyed !!



note right of User #aqua
So far only simple changes in the ui layout, let's see how easy it is to add new functionality to the system.
We argue it is as simple as editing a Spreadsheet/Excel, anybody who has used Excel with a few formulas can use Cloudev.
end note

@enduml